From 9f96b563f6ed532e56984a4f098700f05e8aaafd Mon Sep 17 00:00:00 2001
From: Florian Franzmann <bwlf@bandrate.org>
Date: Sun, 1 Dec 2019 18:42:11 +0100
Subject: [PATCH 29/35] Cleanup: catch exception by const reference

---
 src/Database.cpp | 2 +-
 1 file changed, 1 insertion(+), 1 deletion(-)

diff --git a/src/Database.cpp b/src/Database.cpp
index acb8965..706be16 100644
--- a/src/Database.cpp
+++ b/src/Database.cpp
@@ -34,7 +34,7 @@ void Database::open(const std::string& fname)
 }
 		con=shared_connection(new autoclosed_con(db));
 
-	}catch(std::runtime_error e){
+	}catch(const std::runtime_error& e){
 		if(db != nullptr) {
 			sqlite3_close(db);
 
-- 
2.24.0

